# Generated by Django 2.1.3 on 2018-12-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlqueue',
            name='downloadStage',
            field=models.CharField(default='init', max_length=256),
        ),
    ]
