# Generated by Django 2.1.3 on 2018-12-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0002_auto_20181221_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlqueue',
            name='processName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='crawlqueue',
            name='startFinYear',
            field=models.CharField(default='18', max_length=2),
        ),
    ]
