# Generated by Django 2.1.3 on 2018-12-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0003_auto_20181222_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='muster',
            name='newMusterURL',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
