# Generated by Django 2.1.3 on 2018-12-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0004_muster_newmusterurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlqueue',
            name='musterDownloadAccuracy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
