# Generated by Django 2.1.3 on 2019-01-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0006_auto_20181223_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='muster',
            name='newMusterFormat',
            field=models.BooleanField(default=True),
        ),
    ]
