# Generated by Django 2.1.3 on 2019-01-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0007_muster_newmusterformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayatstat',
            name='nicDaysDemanded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
