# Generated by Django 2.1.3 on 2019-01-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0008_panchayatstat_nicdaysdemanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayatstat',
            name='zeroMusters',
            field=models.BooleanField(default=False),
        ),
    ]
