# Generated by Django 2.1.3 on 2019-01-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0009_panchayatstat_zeromusters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panchayatstat',
            name='jobcardRegisterCrawlDate',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='libtechWorkDaysPanchayatwise',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='mustersDownloaded',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='mustersPendingProcessing',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='mustersProcessed',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='nicJobcardsTotal',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='nicTotalDaysProvided',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='nicTotalWages',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='nicWorkersTotal',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='totalInvalid',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='totalInvalidPercentage',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='totalPending',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='totalPendingPercentage',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='totalRejected',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='totalRejectedPercentage',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='totalTransactions',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='wagelistDownloaded',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='workDaysAccuracyIndex',
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='mustersPendingDownloadPCT',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='wagelistPendingDownloadPCT',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
