# Generated by Django 2.1.3 on 2019-01-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0010_auto_20190106_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panchayatstat',
            name='libtechCreditedWages',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='libtechPendingWages',
        ),
        migrations.RemoveField(
            model_name='panchayatstat',
            name='libtechRejectedWages',
        ),
    ]
