# Generated by Django 2.1.3 on 2019-01-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0011_auto_20190106_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayatstat',
            name='libtechCreditedWagesPCT',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='libtechPendingWagesPCT',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='libtechRejectedWagesPCT',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
