# Generated by Django 2.1.3 on 2019-01-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0012_auto_20190106_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayatstat',
            name='isDataAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
