# Generated by Django 2.1.3 on 2019-01-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0013_panchayatstat_isdataavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayatstat',
            name='libtechCreditedWages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='libtechPendingWages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='libtechRejectedWages',
            field=models.IntegerField(default=0),
        ),
    ]
