# Generated by Django 2.1.3 on 2019-01-11 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0014_auto_20190106_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='demandWorkDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDemandDate', models.DateField()),
                ('daysDemanded', models.PositiveSmallIntegerField()),
                ('demandExists', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('musterIndex', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daysProvided', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daysWorked', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dayWage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('totalWage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('musterStatus', models.CharField(blank=True, max_length=64, null=True)),
                ('accountNo', models.CharField(blank=True, max_length=256, null=True)),
                ('bankName', models.CharField(blank=True, max_length=256, null=True)),
                ('branchName', models.CharField(blank=True, max_length=256, null=True)),
                ('branchCode', models.CharField(blank=True, max_length=256, null=True)),
                ('creditedDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('rejectedFlag', models.BooleanField(default=False)),
                ('isCredited', models.BooleanField(default=False)),
                ('isNICDelayedPayment', models.BooleanField(default=False)),
                ('isNICDelayAccounted', models.BooleanField(default=False)),
                ('isDelayedPayment', models.BooleanField(default=False)),
                ('nicDelayDays', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delayDays', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('paymentDelay', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ftoDelay', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('curWagelist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Wagelist')),
                ('dpTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.DPTransaction')),
                ('muster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Muster')),
                ('wagelist', models.ManyToManyField(blank=True, related_name='dwdWagelist', to='nrega.Wagelist')),
                ('wagelistTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.WagelistTransaction')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Worker')),
            ],
            options={
                'db_table': 'demandWorkDetail',
            },
        ),
        migrations.AlterUniqueTogether(
            name='demandworkdetail',
            unique_together={('worker', 'workDemandDate')},
        ),
    ]
