# Generated by Django 2.1.3 on 2019-01-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0015_auto_20190111_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandworkdetail',
            name='daysDemanded',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
