# Generated by Django 2.1.3 on 2019-01-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0016_auto_20190111_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandworkdetail',
            name='daysAllocated',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
