# Generated by Django 2.1.3 on 2019-01-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0017_demandworkdetail_daysallocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandworkdetail',
            name='demandID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
