# Generated by Django 2.1.3 on 2019-01-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0018_demandworkdetail_demandid'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandworkdetail',
            name='finyear',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
