# Generated by Django 2.1.3 on 2019-01-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0019_demandworkdetail_finyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandworkdetail',
            name='workAllocatedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
