# Generated by Django 2.1.3 on 2019-01-15 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0020_demandworkdetail_workallocateddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MISReportURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finyear', models.CharField(max_length=2)),
                ('contentFileURL', models.URLField(blank=True, max_length=2048, null=True)),
                ('demandRegisterURL', models.URLField(blank=True, max_length=2048, null=True)),
                ('delayPaymentURL', models.URLField(blank=True, max_length=2048, null=True)),
                ('ftoURL', models.URLField(blank=True, max_length=2048, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.State')),
            ],
            options={
                'db_table': 'misReportURL',
            },
        ),
    ]
