# Generated by Django 2.1.3 on 2019-01-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0021_misreporturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayatstat',
            name='nicEmploymentProvided',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='nicJobcardsTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='nicWorkersTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
