# Generated by Django 2.1.3 on 2019-01-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0022_auto_20190117_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlqueue',
            name='source',
            field=models.CharField(default='test', max_length=256),
        ),
    ]
