# Generated by Django 2.1.3 on 2019-01-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0023_crawlqueue_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayatstat',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
