# Generated by Django 2.1.3 on 2019-01-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0024_panchayatstat_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayatstat',
            name='libtechDemandDays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
