# Generated by Django 2.1.3 on 2019-01-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0025_panchayatstat_libtechdemanddays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcardstat',
            old_name='daysProvided',
            new_name='musterDaysProvided',
        ),
        migrations.AddField(
            model_name='jobcardstat',
            name='musterDaysWorked',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobcardstat',
            name='nicDaysDemanded',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='nicDaysProvided',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
