# Generated by Django 2.1.3 on 2019-01-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0026_auto_20190121_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panchayatstat',
            old_name='libtechWorkDaysProvided',
            new_name='musterProvidedDays',
        ),
        migrations.RenameField(
            model_name='panchayatstat',
            old_name='nicWorkDays',
            new_name='musterWorkedDays',
        ),
    ]
