# Generated by Django 2.1.3 on 2019-01-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0028_auto_20190121_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcardstat',
            old_name='daysDemanded',
            new_name='jobcardDaysDemanded',
        ),
        migrations.RenameField(
            model_name='jobcardstat',
            old_name='daysWorked',
            new_name='jobcardDaysWorked',
        ),
    ]
