# Generated by Django 2.1.3 on 2019-01-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0029_auto_20190121_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panchayatstat',
            old_name='musterProvidedDays',
            new_name='musterDaysProvided',
        ),
        migrations.RenameField(
            model_name='panchayatstat',
            old_name='musterWorkedDays',
            new_name='musterDaysWorked',
        ),
    ]
