# Generated by Django 2.1.3 on 2019-02-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0030_auto_20190121_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muster',
            name='musterURL',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='muster',
            name='newMusterURL',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
