# Generated by Django 2.1.3 on 2019-02-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0031_auto_20190207_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNo', models.CharField(max_length=256)),
                ('finyear', models.CharField(max_length=2)),
                ('isComplete', models.BooleanField(default=False)),
                ('isDownloaded', models.BooleanField(default=False)),
                ('downloadDate', models.DateTimeField(blank=True, null=True)),
                ('errorDate', models.DateTimeField(blank=True, null=True)),
                ('isError', models.BooleanField(default=False)),
                ('downloadAttemptCount', models.PositiveSmallIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block')),
            ],
            options={
                'db_table': 'rejectedPayment',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rejectedpayment',
            unique_together={('referenceNo', 'block', 'finyear')},
        ),
    ]
