# Generated by Django 2.1.3 on 2019-02-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0032_auto_20190208_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedpayment',
            name='contentFileURL',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='url',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
