# Generated by Django 2.1.3 on 2019-02-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0034_auto_20190208_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftotransaction',
            name='ftoIndex',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
