# Generated by Django 2.1.3 on 2019-02-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0035_auto_20190208_1853'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ftotransaction',
            unique_together={('fto', 'referenceNo')},
        ),
    ]
