# Generated by Django 2.1.3 on 2019-02-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0036_auto_20190208_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftotransaction',
            name='dwd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.DemandWorkDetail'),
        ),
    ]
