# Generated by Django 2.1.3 on 2019-02-09 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0039_auto_20190209_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandworkdetail',
            name='wt',
            field=models.ManyToManyField(blank=True, related_name='dwdWT', to='nrega.WagelistTransaction'),
        ),
        migrations.AlterField(
            model_name='ftotransaction',
            name='dwd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.DemandWorkDetail'),
        ),
        migrations.AlterField(
            model_name='wagelisttransaction',
            name='dwd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.DemandWorkDetail'),
        ),
    ]
