# Generated by Django 2.1.3 on 2019-02-11 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0047_auto_20190211_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandworkdetail',
            name='wagelist',
        ),
        migrations.RemoveField(
            model_name='demandworkdetail',
            name='wagelistTransaction',
        ),
        migrations.RemoveField(
            model_name='demandworkdetail',
            name='wt',
        ),
        migrations.AlterField(
            model_name='ftotransaction',
            name='dwd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.DemandWorkDetail'),
        ),
        migrations.AlterField(
            model_name='wagelisttransaction',
            name='dwd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.DemandWorkDetail'),
        ),
    ]
