# Generated by Django 2.1.3 on 2019-02-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0048_auto_20190211_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftotransaction',
            name='dwd',
        ),
        migrations.RemoveField(
            model_name='wagelisttransaction',
            name='dwd',
        ),
    ]
