# Generated by Django 2.1.3 on 2019-02-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0049_auto_20190211_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daysAllocated', models.PositiveSmallIntegerField(default=0)),
                ('workAllocatedDate', models.DateField(blank=True, null=True)),
                ('finyear', models.CharField(blank=True, max_length=2, null=True)),
                ('amountDue', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('muster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Muster')),
                ('workDemand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.WorkDemand')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Worker')),
            ],
            options={
                'db_table': 'workPayment',
            },
        ),
        migrations.AlterUniqueTogether(
            name='workpayment',
            unique_together={('worker', 'muster')},
        ),
    ]
