# Generated by Django 2.1.3 on 2019-02-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0050_auto_20190211_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdemand',
            name='workPayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.WorkPayment'),
        ),
    ]
