# Generated by Django 2.1.3 on 2019-02-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0051_workdemand_workpayment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workdemand',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='workdemand',
            name='workPayment',
        ),
        migrations.RemoveField(
            model_name='workdemand',
            name='worker',
        ),
        migrations.AlterUniqueTogether(
            name='workdetail',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='workdetail',
            name='curWagelist',
        ),
        migrations.RemoveField(
            model_name='workdetail',
            name='dpTransaction',
        ),
        migrations.RemoveField(
            model_name='workdetail',
            name='muster',
        ),
        migrations.RemoveField(
            model_name='workdetail',
            name='wagelist',
        ),
        migrations.RemoveField(
            model_name='workdetail',
            name='wagelistTransaction',
        ),
        migrations.RemoveField(
            model_name='workdetail',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='workpayment',
            name='workDemand',
        ),
        migrations.DeleteModel(
            name='WorkDemand',
        ),
        migrations.DeleteModel(
            name='WorkDetail',
        ),
    ]
