# Generated by Django 2.1.3 on 2019-02-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0052_auto_20190211_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDemandDate', models.DateField(db_index=True)),
                ('daysDemanded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('demandID', models.CharField(blank=True, max_length=256, null=True)),
                ('workAllocatedDate', models.DateField(blank=True, null=True)),
                ('daysAllocated', models.PositiveSmallIntegerField(default=0)),
                ('demandExists', models.BooleanField(default=True)),
                ('finyear', models.CharField(blank=True, max_length=2, null=True)),
                ('amountDue', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Worker')),
            ],
            options={
                'db_table': 'workDetail',
            },
        ),
        migrations.AlterUniqueTogether(
            name='workdetail',
            unique_together={('worker', 'workDemandDate')},
        ),
    ]
