# Generated by Django 2.1.3 on 2019-02-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0053_auto_20190211_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetail',
            name='muster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Muster'),
        ),
    ]
