# Generated by Django 2.1.3 on 2019-02-12 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0055_auto_20190211_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetail',
            name='accountNo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='bankName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='branchCode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='branchName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='creditedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='curWagelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.Wagelist'),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='dayWage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='daysProvided',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='daysWorked',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='musterStatus',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='totalWage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='wagelist',
            field=models.ManyToManyField(blank=True, related_name='wdWagelist', to='nrega.Wagelist'),
        ),
    ]
