# Generated by Django 2.1.3 on 2019-02-13 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0057_muster_allwdfound'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finyear', models.CharField(max_length=2)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('referenceNo', models.CharField(blank=True, max_length=256, null=True)),
                ('processDate', models.DateField(blank=True, null=True)),
                ('rejectionReason', models.CharField(blank=True, max_length=4096, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Block')),
                ('fto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.FTO')),
                ('muster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.Muster')),
                ('wagelist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.Wagelist')),
                ('wd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.WorkDetail')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.Worker')),
            ],
            options={
                'db_table': 'rejectedDetail',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rejectiondetail',
            unique_together={('referenceNo', 'block', 'finyear')},
        ),
    ]
