# Generated by Django 2.1.3 on 2019-02-13 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0058_auto_20190213_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='bankCode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='fto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.FTO'),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='ftoString',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='ifscCode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='muster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.Muster'),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='primaryAccountHolder',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='rejectionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='rejectionReason',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='wagelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.Wagelist'),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='wagelistString',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='wd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.WorkDetail'),
        ),
        migrations.AddField(
            model_name='rejectedpayment',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.Worker'),
        ),
    ]
