# Generated by Django 2.1.3 on 2019-02-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0060_workdetail_rejectedpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejectedpayment',
            old_name='wd',
            new_name='workDetail',
        ),
    ]
