# Generated by Django 2.1.3 on 2019-02-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0061_auto_20190213_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muster',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
