# Generated by Django 2.1.3 on 2019-02-14 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0062_auto_20190213_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagelisttransaction',
            name='workDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.WorkDetail'),
        ),
    ]
