# Generated by Django 2.1.3 on 2019-02-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0064_wagelist_allwdfound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wagelisttransaction',
            name='workDetail',
        ),
    ]
