# Generated by Django 2.1.3 on 2019-02-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0066_auto_20190214_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wagelisttransaction',
            name='workDetail',
        ),
    ]
