# Generated by Django 2.1.3 on 2019-02-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0069_remove_workdetail_wagelisttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetail',
            name='wagelistTransaction',
            field=models.ManyToManyField(blank=True, related_name='wdWglTrn', to='nrega.WagelistTransaction'),
        ),
    ]
