# Generated by Django 2.1.3 on 2019-02-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0070_workdetail_wagelisttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagelisttransaction',
            name='rejectedPayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.RejectedPayment'),
        ),
    ]
