# Generated by Django 2.1.3 on 2019-02-16 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0071_wagelisttransaction_rejectedpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetail',
            name='dpTransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.DPTransaction'),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='isNICDelayAccounted',
            field=models.BooleanField(default=False),
        ),
    ]
