# Generated by Django 2.1.3 on 2019-02-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0072_auto_20190216_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='oldID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crawlqueue',
            name='downloadStage',
            field=models.CharField(default='A1_init', max_length=256),
        ),
    ]
