# Generated by Django 2.1.3 on 2019-02-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0074_auto_20190223_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDemandDate', models.DateField(blank=True, db_index=True, null=True)),
                ('workAllocatedDate', models.DateField(blank=True, db_index=True, null=True)),
                ('daysDemanded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('demandID', models.CharField(blank=True, max_length=256, null=True)),
                ('daysAllocated', models.PositiveSmallIntegerField(default=0)),
                ('demandExists', models.BooleanField(default=True)),
                ('finyear', models.CharField(blank=True, max_length=2, null=True)),
                ('amountDue', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('daysProvided', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daysWorked', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dayWage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('totalWage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('musterStatus', models.CharField(blank=True, max_length=64, null=True)),
                ('accountNo', models.CharField(blank=True, max_length=256, null=True)),
                ('bankName', models.CharField(blank=True, max_length=256, null=True)),
                ('branchName', models.CharField(blank=True, max_length=256, null=True)),
                ('branchCode', models.CharField(blank=True, max_length=256, null=True)),
                ('creditedDate', models.DateField(blank=True, null=True)),
                ('isNICDelayAccounted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('curWagelist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.Wagelist')),
                ('dpTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.DPTransaction')),
                ('muster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Muster')),
                ('rejectedPayment', models.ManyToManyField(blank=True, related_name='wpRejPay', to='nrega.RejectedPayment')),
                ('wagelist', models.ManyToManyField(blank=True, related_name='wpWagelist', to='nrega.Wagelist')),
                ('wagelistTransaction', models.ManyToManyField(blank=True, related_name='wpWglTrn', to='nrega.WagelistTransaction')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.Worker')),
            ],
            options={
                'db_table': 'workPayment',
            },
        ),
        migrations.AlterUniqueTogether(
            name='workpayment',
            unique_together={('worker', 'workDemandDate', 'workAllocatedDate')},
        ),
    ]
