# Generated by Django 2.1.3 on 2019-02-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0075_auto_20190223_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedpayment',
            name='workPayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.WorkPayment'),
        ),
        migrations.AddField(
            model_name='rejectiondetail',
            name='wp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.WorkPayment'),
        ),
        migrations.AddField(
            model_name='wagelisttransaction',
            name='workPayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.WorkPayment'),
        ),
    ]
