# Generated by Django 2.1.3 on 2019-02-24 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0076_auto_20190223_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='test', max_length=256)),
                ('processName', models.CharField(blank=True, max_length=256, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('startFinYear', models.CharField(default='18', max_length=2)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('attemptCount', models.PositiveSmallIntegerField(default=0)),
                ('stepError', models.BooleanField(default=False)),
                ('downloadAttemptCount', models.PositiveSmallIntegerField(default=0)),
                ('crawlStartDate', models.DateTimeField(blank=True, null=True)),
                ('crawlAttemptDate', models.DateTimeField(blank=True, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('inProgress', models.BooleanField(default=False)),
                ('isError', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Block')),
            ],
            options={
                'db_table': 'crawlRequest',
            },
        ),
        migrations.CreateModel(
            name='CrawlState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'crawlState',
            },
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='crawlState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.CrawlState'),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='libtechTag',
            field=models.ManyToManyField(blank=True, related_name='crawlReqeustTag', to='nrega.LibtechTag'),
        ),
        migrations.AddField(
            model_name='crawlrequest',
            name='panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Panchayat'),
        ),
    ]
