# Generated by Django 2.1.3 on 2019-02-24 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0077_auto_20190224_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='crawlState',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrega.CrawlState'),
        ),
    ]
