# Generated by Django 2.1.3 on 2019-02-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0078_auto_20190224_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlstate',
            name='isBlockLevel',
            field=models.BooleanField(default=False),
        ),
    ]
