# Generated by Django 2.1.3 on 2019-02-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0079_crawlstate_isblocklevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlstate',
            name='iterateFinYear',
            field=models.BooleanField(default=True),
        ),
    ]
