# Generated by Django 2.1.3 on 2019-02-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0080_crawlstate_iteratefinyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlstate',
            name='needFullBlockData',
            field=models.BooleanField(default=False),
        ),
    ]
