# Generated by Django 2.1.3 on 2019-02-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0081_crawlstate_needfullblockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayatstat',
            name='jobcardDownloadAccuracy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='musterDownloadAccuracy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='wagelistDownloadAccuracy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
