# Generated by Django 2.1.3 on 2019-02-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0082_auto_20190226_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panchayatstat',
            old_name='mustersPendingDownload',
            new_name='mustersDownloaded',
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='mustersPending',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='wagelistDownloaded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panchayatstat',
            name='wagelistInComplete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
