# Generated by Django 2.1.3 on 2019-02-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0083_auto_20190226_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftotransaction',
            name='favorBankAPB',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
