# Generated by Django 2.1.3 on 2019-02-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0084_ftotransaction_favorbankapb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftotransaction',
            name='IINBankAPB',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
