# Generated by Django 2.1.3 on 2019-02-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0085_ftotransaction_iinbankapb'),
    ]

    operations = [
        migrations.AddField(
            model_name='fto',
            name='allJobcardFound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fto',
            name='allWagelistFound',
            field=models.BooleanField(default=False),
        ),
    ]
