# Generated by Django 2.1.3 on 2019-02-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0086_auto_20190226_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftoIndex', models.PositiveSmallIntegerField(db_index=True)),
                ('creditedAmount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('referenceNo', models.CharField(blank=True, max_length=256, null=True)),
                ('transactionDate', models.DateField(blank=True, null=True)),
                ('processDate', models.DateField(blank=True, null=True)),
                ('rejectionReason', models.CharField(blank=True, max_length=4096, null=True)),
                ('primaryAccountHolder', models.CharField(blank=True, max_length=4096, null=True)),
                ('favorBankAPB', models.CharField(blank=True, max_length=256, null=True)),
                ('IINBankAPB', models.CharField(blank=True, max_length=256, null=True)),
                ('jobcardRaw', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('fto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrega.FTO')),
                ('jobcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Jobcard')),
                ('wagelist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrega.Wagelist')),
            ],
            options={
                'db_table': 'paymentTransaction',
            },
        ),
        migrations.AlterUniqueTogether(
            name='paymenttransaction',
            unique_together={('fto', 'ftoIndex')},
        ),
    ]
