# Generated by Django 2.1.3 on 2019-03-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0087_auto_20190226_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlstate',
            name='maxhour',
            field=models.PositiveSmallIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='crawlstate',
            name='minhour',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
