# Generated by Django 2.1.3 on 2019-04-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrega', '0088_auto_20190301_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrequest',
            name='endFinYear',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
