delayURLs={
      "27_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=RAJASTHAN&state_code=27&fin_year=2017-2018&source=national&rbl=0&Digest=GBtg80J+Fag8JggMJsaQow",
      "27_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=RAJASTHAN&state_code=27&fin_year=2018-2019&source=national&rbl=0&Digest=6xYCn7uUZI1yfBGFWIKKIw",
      "34_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=JHARKHAND&state_code=34&fin_year=2018-2019&source=national&rbl=0&Digest=C9zPwbzOJicn+Q39Puxk1g",
      "34_18": "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=JHARKHAND&state_code=34&fin_year=2017-2018&source=national&rbl=0&Digest=g24tni1Y6dlC1HwJeV9kMA",
      "05_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=BIHAR&state_code=05&fin_year=2018-2019&source=national&rbl=0&Digest=gSeBDgRxGSRDm7sDStHYzA",
      "05_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=BIHAR&state_code=05&fin_year=2017-2018&source=national&rbl=0&Digest=GTx25n0LyB7fQG5Tuz1sHA",
      "24_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=ODISHA&state_code=24&fin_year=2018-2019&source=national&rbl=0&Digest=Q6TFejfbKbTcrJ+KPHWalg",
      "24_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=ODISHA&state_code=24&fin_year=2018-2019&source=national&rbl=0&Digest=Q6TFejfbKbTcrJ+KPHWalg",
      "16_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=KERALA&state_code=16&fin_year=2017-2018&source=national&rbl=0&Digest=HitbdjGmIQ2QZCs35LRjoA",
      "16_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=KERALA&state_code=16&fin_year=2018-2019&source=national&rbl=0&Digest=GxNOh8vl0lBLNoOqbQwYBA",
      "33_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=CHHATTISGARH&state_code=33&fin_year=2017-2018&source=national&rbl=0&Digest=HzL26gQOT6hYDnLRbbzglw",
      "33_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=CHHATTISGARH&state_code=33&fin_year=2018-2019&source=national&rbl=0&Digest=CqeWy/ccjLEyk1C9VIei0g",
      "15_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=KARNATAKA&state_code=15&fin_year=2017-2018&source=national&rbl=0&Digest=lVjEZ3KqqDdQjVrIKhhFaw",
      "15_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=KARNATAKA&state_code=15&fin_year=2018-2019&source=national&rbl=0&Digest=EizTymbFaCM/MNUYcI2L6g",
      "17_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=MADHYA%20PRADESH&state_code=17&fin_year=2017-2018&source=national&rbl=0&Digest=/5UTj0M+CWJym8n0rrmNlQ",
      "17_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=MADHYA%20PRADESH&state_code=17&fin_year=2018-2019&source=national&rbl=0&Digest=jmufOVyiFoJBmhC5GEVPHA",
      "31_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=UTTAR%20PRADESH&state_code=31&fin_year=2017-2018&source=national&rbl=0&Digest=DKTLIo3zI/1GAJSfavBMVA",
      "31_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=UTTAR%20PRADESH&state_code=31&fin_year=2018-2019&source=national&rbl=0&Digest=VbjMfa+eIsOZnOkOEUTN2A",
      "32_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=WEST%20BENGAL&state_code=32&fin_year=2017-2018&source=national&rbl=0&Digest=gXBWnD9d8Q6M79A8kbU2gQ",
      "32_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=WEST%20BENGAL&state_code=32&fin_year=2018-2019&source=national&rbl=0&Digest=YYf9Ex/W7RSQJa2iQcG75Q",
      "18_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=MAHARASHTRA&state_code=18&fin_year=2017-2018&source=national&rbl=0&Digest=TNrlfbJcBHnGjnoZoCzH+A",
      "18_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=MAHARASHTRA&state_code=18&fin_year=2018-2019&source=national&rbl=0&Digest=YU+c/cSMbSUAyD2TXE4ksw",
      "01_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=ANDAMAN%20AND%20NICOBAR&state_code=01&fin_year=2017-2018&source=national&rbl=0&Digest=PUfdsq28KM4jxdgmCRmsrw",
      "01_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=ANDAMAN%20AND%20NICOBAR&state_code=01&fin_year=2018-2019&source=national&rbl=0&Digest=T0oyTpJs/MwJRgu8mm5rDg",
      "02_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=ANDHRA%20PRADESH&state_code=02&fin_year=2017-2018&source=national&rbl=0&Digest=mnk1spj2Mihdra+fnl0GIA",
      "02_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=ANDHRA%20PRADESH&state_code=02&fin_year=2018-2019&source=national&rbl=0&Digest=FUvQbUDK4bNLTIuz+aPsPQ",
      "03_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=ARUNACHAL%20PRADESH&state_code=03&fin_year=2017-2018&source=national&rbl=0&Digest=p4LexUEKM8NQVfHTWNcBWA",
      "03_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=ARUNACHAL%20PRADESH&state_code=03&fin_year=2018-2019&source=national&rbl=0&Digest=NsALjVw01uCwc7paYF2PPg",
      "04_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=ASSAM&state_code=04&fin_year=2017-2018&source=national&rbl=0&Digest=b6VHaWKCtqN53r+TCRNmyA",
      "04_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=ASSAM&state_code=04&fin_year=2018-2019&source=national&rbl=0&Digest=raoWATL6mOk6WiZLfgeKxA",
      "11_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=GUJARAT&state_code=11&fin_year=2017-2018&source=national&rbl=0&Digest=Lw7UdU9BWVQONwPG6O93Ww",
      "11_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=GUJARAT&state_code=11&fin_year=2018-2019&source=national&rbl=0&Digest=N9OCGhZSa2aMXaKyeRo0Iw",
      "12_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=HARYANA&state_code=12&fin_year=2017-2018&source=national&rbl=0&Digest=caubDzfYN9wnhzBEi8+tEA",
      "12_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=HARYANA&state_code=12&fin_year=2018-2019&source=national&rbl=0&Digest=NEd/y94J5JOaGNKvYy9wgg",
      "13_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=HIMACHAL%20PRADESH&state_code=13&fin_year=2017-2018&source=national&rbl=0&Digest=KUmYhRlR4RAPwku2nfjRrA",
      "13_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=HIMACHAL%20PRADESH&state_code=13&fin_year=2018-2019&source=national&rbl=0&Digest=DkuS5bNEn0qddywZH4P5Dg",
      "26_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=PUNJAB&state_code=26&fin_year=2017-2018&source=national&rbl=0&Digest=hdwbwujVoy8RSKJ3CrHDvw",
      "26_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=PUNJAB&state_code=26&fin_year=2018-2019&source=national&rbl=0&Digest=UB4JAQPykB1JYSmkFHRNbg",
      "29_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=TAMIL%20NADU&state_code=29&fin_year=2017-2018&source=national&rbl=0&Digest=1m50HJbNB/i1DvB5NKDh1Q",
      "29_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=TAMIL%20NADU&state_code=29&fin_year=2018-2019&source=national&rbl=0&Digest=ofXRjvKLaVmO3Mmt7jOmdw",
      "14_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=JAMMU%20AND%20KASHMIR&state_code=14&fin_year=2017-2018&source=national&rbl=0&Digest=R/k/9q27I9HvL9bXXuXr3w",
      "14_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=JAMMU%20AND%20KASHMIR&state_code=14&fin_year=2018-2019&source=national&rbl=0&Digest=Z9Sh5t7OX+gqOaJqXP7Rng",
      "35_18" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=UTTARAKHAND&state_code=35&fin_year=2017-2018&source=national&rbl=0&Digest=hBo5S3o6PdxD5Gm0yQTj4w",
      "35_19" : "http://mnregaweb4.nic.in/netnrega/state_html/delay_comp.aspx?rb_mon=Y&page=S&state_name=UTTARAKHAND&state_code=35&fin_year=2018-2019&source=national&rbl=0&Digest=2SFV8oXmVrAdqsK8hel04w",
      "88_18" : "",
      "88_19" : "",




        }
